sudo: required
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - meteor --version
script:
  - npm run eslint -s
  - meteor create --bare test
  - cd test
  - meteor npm i --save selenium-webdriver@3 chromedriver
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=chrome meteor --once test-packages --driver-package meteortesting:mocha ../
